apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.secrets.dbPassword }}"
  API_KEY:     "{{ .Values.secrets.apiKey }}"
  JWT_SECRET:  "{{ .Values.secrets.jwtSecret }}"
